spring:
  application:
    name: petective
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PWD}
  sql:
    init:
      mode: always
      encoding: UTF-8
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        storage_engine: innodb
        format_sql: true
        use_sql_comments: true
    hibernate:
      #hbm2ddl.auto: update
      ddl-auto: update #create: 매번 테이블 새로 생성 / update: 테이블 상태 유지 / validate:
    open-in-view: false
    show_sql: true

  cloud:
    aws:
      s3:
        bucket: petective-image
      region:
        static: ap-northeast-2
      stack:
        auto: false
      credentials:
        access-key: ${S3_ACCESS_KEY}
        secret-key: ${S3_SECRET_KEY}






jwt:
  issuer: ${JWT_ISSUER}
  secret_key: ${JWT_SECRET_KEY}