spring:
  application:
    name: petective
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-petective.cnyceqa06ndp.ap-northeast-2.rds.amazonaws.com:3306/petective?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
    username: mungtamjung
    password: mungtamjung2024
  sql:
    init:
      mode: always
      encoding: UTF-8
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        storage_engine: innodb
        format_sql: true
        use_sql_comments: true
    hibernate:
      #hbm2ddl.auto: update
      ddl-auto: update #create: 매번 테이블 새로 생성 / update: 테이블 상태 유지 / validate:
    open-in-view: false
    show_sql: true

  cloud:
    aws:
      s3:
        bucket: petective-image
      region:
        static: ap-northeast-2
      stack:
        auto: false
      credentials:
        access-key: AKIAU6GDWPGGPPRP2XOP
        secret-key: 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






jwt:
  issuer: mungtamjung
  secret_key: pectectivemungtamjungpectectivemungtamjungpectectivemungtamjung